### ISSUE TITLE
UndefVarError: Image not defined

### ISSUE THREAD

**Issue by dylanfesta** [loganwilliams/Pyramids.jl#4]
It seems that after the latest updated I cannot use Pyramids anymore... 
there is no type called "Image" 
This is what happens: 

julia> Pkg.test("Pyramids")
INFO: Testing Pyramids

WARNING: deprecated syntax "abstract PyramidType" at /home/dfesta/.julia/v0.6/Pyramids/src/Pyramids.jl:10.
Use "abstract type PyramidType end" instead.

WARNING: deprecated syntax "abstract SimplePyramid<:PyramidType" at /home/dfesta/.julia/v0.6/Pyramids/src/Pyramids.jl:11.
Use "abstract type SimplePyramid<:PyramidType end" instead.
ERROR: LoadError: LoadError: UndefVarError: Image not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
while loading /home/dfesta/.julia/v0.6/Pyramids/src/Pyramids.jl, in expression starting on line 521
while loading /home/dfesta/.julia/v0.6/Pyramids/test/runtests.jl, in expression starting on line 1

I think it can be easily solved by erasing all the parts in which im::Image appears as function argument.

**Comment by loganwilliams** [comment]
This should be fixed in 2ef607c3cf6b5892b7b68e506b1a5e22d8ea1b81. It will be Pyramid v0.0.2 when METADATA.jl is updated.
